### ISSUE TITLE
Front desk > Icon tool tips do not work.

### ISSUE THREAD

**Issue by Stardog** [AppStateESS/counseling#27]

**Comment by Stardog** [comment]
Take the tooltip off the icon itself and put it on a span. FontAwesome svg conversion blows out the listener.

**Comment by eberhardtm** [comment]
I don't see which tooltips yours talking about. I don't see any on the live version

**Comment by Stardog** [comment]
There needs to be a student in walk ins or appointments. They have an icon to the left showing their status. Hover your mouse over it and a tool tip with the reason for their visit will show.
